chat_app/urls.py
from django.conf.urls import include, url
from chat_app import views
app_name='chat_app'
urlpatterns = [
    url(r'^$',  views.about, name='about'),
    url(r'^new/$', views.new_room, name='new_room'),
    url(r'^(?P<label>[\w-]{,50})/$', views.chat_room, name='chat_room'),
]

django_blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog_app.views import IndexView,CreateUser,PostCreate,PostDetail,UserLogin
from blog_app import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',login_required(IndexView.as_view()),name='index'),
    url(r'^login/$', UserLogin.as_view(redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^signup/$', CreateUser.as_view(), name='signup'),
    url(r'^create/$', PostCreate.as_view(), name='post'),
    url(r'^post_detail/(?P<pk>[0-9]+)/$', PostDetail.as_view(), name='post_detail'),
    url(r'^user_comment/$',views.user_comment, name='user_comment'),
    url(r'^comments/$',views.comments, name='comments'),
    url(r'^chat_app/',include('chat_app.urls',namespace='channel_app')),
]

templates/base_template.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {%block title%}<title>Blog Application</title>{%endblock%}
  </head>
  <body>
    <div class="container">
      {%block header%}
      <header>
        <nav class="navbar navbar-default">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index'%}">Blog</a>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{%url 'index'%}">Home</a></li>
              {% if user.is_authenticated%}
              <li><a href="{%url 'logout'%}">Logout</a></li>
              <li><a href="#">My Profile</a></li>
              <li><a href="#"><span class="glyphicon glyphicon-tint" aria-hidden="true"></span><span class="badge">1</span></a></li>
              {%else%}
              <li><a href="{%url 'login'%}">Login</a></li>
              <li><a href="{%url 'signup'%}">SignUp</a></li>
              {%endif%}
              <li><a href="#">About Us</a></li>
              <li><a href="{%url 'channel_app:about'%}">Chat App</a></li>
            </ul>
          </div>
        </nav>
      </header>
      {%endblock%}
      {%block content%}
      <div class="row">
        <h1>Index page</h1>
      </div>
      {%endblock%}
    </div>
    <script src="//cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>
  </body>
</html>

templates/index.html
{%extends 'base_template.html'%}
{%block content%}
<div class="row" id="post_list">
  {%for post in object_list %}
  <div class="col-xs-12 col-sm-12 col-md-offset-4 col-md-4">
    <div class="vcenter" style="box-shadow: 1px 1px 1px 1px #888888;">
      <div class="card" style="padding:20px;">
        <div class="card-block">
          <h5 class="card-title"><a href="{%url 'post_detail' post.id %}">{{post.post_title}}</a><span id=like_{{post.id}} class="pull-right glyphicon glyphicon-heart-empty"></span><br><small class="text-muted"> By {{post.user}} <span>on</span> {{post.created_at}}</small></h5>
          <p class="card-text">
            <a href="{%url 'post_detail' post.id %}" class="btn btn-default">Read More</a>
            <span class="pull-right">
              <a type="button"  data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo" id=det_{{post.id}}>
                <span class="text-muted">{{post.likes}}</span>
                <span class="text-muted">Like  </span>
                <span class="text-muted">{{post.comments}}</span><span class="text-muted">  Comment</span>
              </a>
            </span>
          </p>
        </div>
      </div>
    </div>
  </div>
  {%endfor%}
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Commented by</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="">
          <ul class="list-group msg-list">

          </ul>
        </div>
        <form class="form"  method="post" id="comment-form">
          {% csrf_token %}
          {%for f in form%}
          <div class="form-group">
            {{f}}
          </div>
          {%endfor%}
          <input type="submit" name="name" value="Comment" class="btn btn-primary" id="post_submit">
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="row text-center">
  <a href="{%url 'post'%}" class="btn btn-success">Create Post</a>
</div>
<style media="screen">
.vcenter {
  margin: 15px 0px;
}
</style>
<script type="text/javascript">
$(function() {
    // When we're using HTTPS, use WSS too.
    var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
    // var chatsock = new ReconnectingWebSocket(ws_scheme + '://' + window.location.host + window.location.pathname);
    var chatsock = new ReconnectingWebSocket(ws_scheme + '://' + window.location.host + window.location.pathname);
    console.log(ws_scheme + '://' + window.location.host + window.location.pathname);
    chatsock.onmessage = function(message) {
      console.log(message);
        var data = JSON.parse(message.data);
        // console.log(data);
        var chat = $("#post_list")
        var ele = $("<div class='col-xs-12 col-sm-12 col-md-offset-4 col-md-4'></div>");
        ele.append($("<div class='vcenter' style='box-shadow: 1px 1px 1px 1px #888888;'><div class='card' style='padding:20px;'><div class='card-block'><h5 class='card-title'><a href= /post_detail/"+ data.id + "> " + data.title + " </a><br><small class='text-muted'> By " + data.user + "<span>on </span> " +  data.created + "</small></h5><p class='card-text'><a href= /post_detail/"+ data.id  + " class='btn btn-default'>Read More</a></p></div></div>"));
        // ele.append(
        //   $("<h4 class='card-title'><a href= /post_detail/"+ data.id + "> " + data.title + " </a><br><small class='text-muted'> By " + data.user + "<span>on </span> " +  data.created + "</small></h4>"));
        // ele.append(
        //   $("<p class='card-text'><a href= /post_detail/"+ data.id  + " class='btn btn-default'>Read More</a></p>"));
        chat.append(ele)
    };
//     chatsock.onopen = function() {
//     chatsock.send("hello world");
// }
// // Call onopen directly if socket is already open
// if (chatsock.readyState == WebSocket.OPEN) chatsock.onopen();

});
$('[id^="like_"]').on('click', function(event){
  $(this).toggleClass("glyphicon-heart-empty glyphicon-heart");
   //you can list several class names
});
var x
$('[id^="det_"]').on('click', function(event){
  $(".msg-list").empty();
  if ($('#exampleModal').hasClass('in')) {

  }
   x = (this.id).split("_")[1];
  console.log(x)
  $("#comment-form").append($('<input type="hidden" name="post_id" value='+x+'>'))
  console.log("hey yeh");
  $.ajax({
  			    url: "{% url 'comments'  %}",
            type: 'GET',
            data: {'id' : x},
  			    success: function(data) {
              console.log(data);
              console.log(data);
              console.log(data.user_id);
              console.log(data.post_comment);
              console.log(data.post_comment.length);
              for(i in data.user_id){
                console.log(i);
                var $row = $('<li class="list-group-item">'+ data.post_comment[i] + '<small class="text-muted"><span class="pull-right"><strong>By </strong><a href="#">'+ data.user_id[i] + '</a></span></small></li>');
                $('.msg-list').append($row);
              }
              },
              error: function(data) {
                console.log(data);
                        alert('There some problem! try again later!');
                    }
            });
});
$('#comment-form').on('submit', function(event){
  var x = {{post_detail.id}}
  $('#post_submit').prop('disabled',true)
console.log($('#p_com').val());
  $.ajax({
  			    url: '/user_comment/',
            type: $(this).attr('method'),
            data: $(this).serialize(),
  			    success: function(data) {
              console.log(data);
              var $row = $('<li class="list-group-item">'+ $('#p_com').val()  + '<small class="text-muted"><span class="pull-right"><strong>By </strong><a href="#">You</a></span></small></li>');
              $('.msg-list').append($row);
              $('#post_submit').prop('disabled',false)
              $('#p_com').val('')
              },
              error: function(data) {
                $('#post_submit').prop('disabled',false)
                console.log(data);
                        alert('There some problem! try again later!');
                    }
            });
            return false;
});
</script>
{%endblock%}

templates/login.html
{%extends 'base_template.html'%}
{%block content%}
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-3 col-md-offset-4">
    {% if form.errors %}
    <div class="list-group">
      <li class="list-group-item alert alert-danger"><p>Your username and password didn't match. Please try again.</p></li>
    </div>
    {% endif %}
    {% if form.help_text %}
    <span class="help">{{ form.help_text|safe }}</span>
    {% endif %}
    <form class="form" method="post">
      {%csrf_token%}
      {%for f in form%}
      <div class="form-group">
        <div class="input-group">

          {% if forloop.counter == 1 %}
          <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
          {% endif %}
          {% if forloop.counter == 2 %}
          <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></span>
          {% endif %}
          {{f}}
        </div>
      </div>
      {%endfor%}
      <input type="submit" value="Login" class="btn btn-default">
    </form>
  </div>
</div>
{%endblock%}

templates/post.html
{%extends 'base_template.html'%}
{%block content%}
<form class="form" method="post">
  {%csrf_token%}
  {{form.as_p}}
  <input type="submit" name="Post" class="btn btn-default" data-disable="false">
</form>
{%endblock%}

templates/post_detail.html
{%extends 'base_template.html'%}
{%block content%}
<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <div class="jumbotron">
      <div class="row text-center">
        <h1>{{post_detail.post_title}}</h1>
      </div>
      <hr>
      <div class="text-center" style="padding:10px;">
        <p>
          {{post_detail.post_text}}
        </p>
      </div>
      <div class="">
        <ul class="list-group msg-list">
          {%for com in comments%}
          <li class="list-group-item">{{com.post_comment}}</i>
            <small class="text-muted"><span class="pull-right"><strong>By </strong><a href="#">{{com.user_id}}</a></span></small>
          </li>
          {%endfor%}
        </ul>
      </div>
      <form class="form"  method="post" id="comment-form">
        {% csrf_token %}
        {%for f in form%}
        <div class="col-md-10 col-sm-8 col-xs-12">
          <div class="form-group">
            <input type="hidden" name="post_id" value="{{ post_detail.id }}">
            {{f}}
          </div>
        </div>
        {%endfor%}
        <div class="col-md-1 col-sm-2">
          <input type="submit" name="name" value="Comment" class="btn btn-primary" id="post_submit">
        </div>
      </form>
    </div>
  </div>
</div>
<style media="screen">
.list-group-item{
margin-top: 10px;
overflow-wrap: break-word;
}
.list-group-item:nth-child(even) {
  background-color: #f5f5f5;
}

</style>
<script type="text/javascript">
$('#comment-form').on('submit', function(event){
  var x = {{post_detail.id}}
  $('#post_submit').prop('disabled',true)
console.log($('#p_com').val());
  $.ajax({
  			    url: '/user_comment/',
            type: $(this).attr('method'),
            data: $(this).serialize(),
  			    success: function(data) {
              console.log(data);
              // var $row = $('<li class="list-group-item">'+$("#p_com").val() + '<small class="text-muted"><span class="pull-right"><strong>By </strong><a href="#">you </a></span></small></li>');
              // // $row+=$('<small class="text-muted"><span class="pull-right"><strong>By </strong><a href="#">' + {{com.user_id}}+ '</a></span></small>')
              // $('.msg-list').append($row);
              $('#post_submit').prop('disabled',false)
              $('#p_com').val('')
              },
              error: function(data) {
                $('#post_submit').prop('disabled',false)
                console.log(data);
                        alert('There some problem! try again later!');
                    }
            });
            return false;
});
$(function() {
    // When we're using HTTPS, use WSS too.
    var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
    // var chatsock = new ReconnectingWebSocket(ws_scheme + '://' + window.location.host + window.location.pathname);
    var chatsock = new ReconnectingWebSocket(ws_scheme + '://' + window.location.host + window.location.pathname);
    console.log(ws_scheme + '://' + window.location.host + window.location.pathname);
    chatsock.onmessage = function(message) {
      console.log(message);
        var data = JSON.parse(message.data);
        console.log(data);
        var $row = $('<li class="list-group-item"> '+ data.post_comment + ' <small class="text-muted"><span class="pull-right"><strong>By </strong><a href="#">'+ data.user_id +'</a></span></small></li>');
        // $row+=$('<small class="text-muted"><span class="pull-right"><strong>By </strong><a href="#">' + {{com.user_id}}+ '</a></span></small>')
        $('.msg-list').append($row);
    };
//     chatsock.onopen = function() {
//     chatsock.send("hello world");
// }
// // Call onopen directly if socket is already open
// if (chatsock.readyState == WebSocket.OPEN) chatsock.onopen();

});
</script>
{%endblock%}

templates/signup.html
{%extends 'base_template.html'%}
{%block content%}
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-4 col-md-offset-4">
    <form class="form" method="post">
      {%csrf_token%}
      {%for f in form%}
      <div class="form-group">
        <div class="input-group">

          {% if forloop.counter == 1 %}
          <span class="input-group-addon" id="basic-addon1">First Name</span>
          {% endif %}
          {% if forloop.counter == 2 %}
          <span class="input-group-addon" id="basic-addon1">Last Name</span>
          {% endif %}
          {% if forloop.counter == 3 %}
          <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
          {% endif %}
          {% if forloop.counter == 4 %}
          <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></span>
          {% endif %}
          {% if forloop.counter == 5 %}
          <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></span>
          {% endif %}
          {% if forloop.counter == 6 %}
          <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></span>
          {% endif %}
          {{f}}
        </div>
        {% if f.errors %}
        <div class="list-group">
          {% for error in f.errors %}
          <li class="list-group-item alert alert-danger"><strong>{{ error|escape }}</strong></li>
          {% endfor %}
        </div>
        {% endif %}
        {% if f.help_text %}
        <span class="help">{{ field.help_text|safe }}</span>
        {% endif %}
      </div>
      {%endfor%}
      <input type="submit" name="SignUp" class="btn btn-primary">
    </form>
  </div>
</div>
{%endblock%}