chat_app/urls.py
from django.conf.urls import include, url
from chat_app import views
app_name='chat_app'
urlpatterns = [
    url(r'^$',  views.about, name='about'),
    url(r'^new/$', views.new_room, name='new_room'),
    url(r'^(?P<label>[\w-]{,50})/$', views.chat_room, name='chat_room'),
]

django_blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog_app.views import IndexView,CreateUser,PostCreate,PostDetail,UserLogin
from blog_app import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',login_required(IndexView.as_view()),name='index'),
    url(r'^login/$', UserLogin.as_view(redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^signup/$', CreateUser.as_view(), name='signup'),
    url(r'^create/$', PostCreate.as_view(), name='post'),
    url(r'^post_detail/(?P<pk>[0-9]+)/$', PostDetail.as_view(), name='post_detail'),
    url(r'^user_comment/$',views.user_comment, name='user_comment'),
    url(r'^comments/$',views.comments, name='comments'),
    url(r'^chat_app/',include('chat_app.urls',namespace='channel_app')),
]

chat_app/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Room(models.Model):
    name = models.TextField()
    label = models.SlugField(unique=True)
    def __str__(self):
        return self.label

class Message(models.Model):
    room = models.ForeignKey(Room, related_name='messages')
    handle = models.TextField()
    message = models.TextField()
    timestamp = models.DateTimeField(default=timezone.now, db_index=True)
    def __str__(self):
        return '[{timestamp}] {handle}: {message}'.format(**self.as_dict())

    @property
    def formatted_timestamp(self):
        return self.timestamp.strftime('%b %-d %-I:%M %p')

    def as_dict(self):
        return {'handle': self.handle, 'message': self.message, 'timestamp': self.formatted_timestamp}

chat_app/views.py
import random
import string
from django.db import transaction
from django.shortcuts import render, redirect
from haikunator import Haikunator
from .models import Room

def about(request):
    return render(request, "chat_app/about.html")

def new_room(request):
    """
    Randomly create a new room, and redirect to it.
    """
    new_room = None
    while not new_room:
        with transaction.atomic():
            haikunator = Haikunator()
            label = haikunator.haikunate()
            if Room.objects.filter(label=label).exists():
                continue
            new_room = Room.objects.create(label=label)
    return redirect('chat_app:chat_room', label=label)

def chat_room(request, label):
    """
    Room view - show the room, with latest messages.
    The template for this view has the WebSocket business to send and stream
    messages, so see the template for where the magic happens.
    """
    # If the room with the given label doesn't exist, automatically create it
    # upon first visit (a la etherpad).
    room, created = Room.objects.get_or_create(label=label)

    # We want to show the last 50 messages, ordered most-recent-last
    messages = reversed(room.messages.order_by('-timestamp')[:50])

    return render(request, "chat_app/room.html", {
        'room': room,
        'messages': messages,
    })

templates/chat_app/about.html
{% extends "base_template.html" %}

{% block content %}
  <h1>Django Channels Example</h1>
  <p class="deck">

  </p>
  <div class="row text-center">
    <p>
      <a class="btn btn-primary" href="{% url 'channel_app:new_room' %}">Create new chat room</a>
    </p>
    <p class="quiet">
      Or, you can visit <code>{{ request.scheme }}://{{ request.get_host }}/any-path-you-want</code>
      to create a arbitrary room or join one whose name you know.
    </p>
  </div>
{% endblock content %}

templates/chat_app/chat_index.html
{%extends 'base_template.html'%}
{%block header%}
<header>
  <nav class="navbar navbar-default">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index'%}">Blog</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{%url 'index'%}">Back to Blog</a></li>
      </ul>
    </div>
  </nav>
</header>
{%endblock%}
{%block content%}
<div class="row text-center">
  <h3>Chat App</h3>
  {% load staticfiles %}
  <h1>{{ room.label }}</h1>
  <p class="quiet">
    Anyone with this URL can join the room and chat:
    <code>{{ request.scheme }}://{{ request.get_host }}/{{ room.label }}</code>
  </p>
  <p>
    <label for="handle">Your name:</label>
    <input id="handle" type="text" placeholder="handle">
  </p>
  <form id="chatform">
    <table id="chat">
      <tbody>
        {% for message in messages %}
          <tr>
            <td>{{ message.formatted_timestamp }}</td>
            <td>{{ message.handle }}</td>
            <td>{{ message.message }}</td>
          </tr>
        {% endfor %}
      </tbody>
      <tfoot>
      <tr>
        <td>Say something:</td>
        <td colspan=2>
          <input id="message" type="text" placeholder="message">
          <button type="submit" id="go">Say it</button>
        </td>
      </tfoot>
    </table>
  </form>
</div>
{%endblock%}

templates/chat_app/room.html
{% extends "base_template.html" %}

{% block content %}
  {% load staticfiles %}
  <h1>{{ room.label }}</h1>
  <p class="quiet">
    Anyone with this URL can join the room and chat:
    <code>{{ request.scheme }}://{{ request.get_host }}/{{ room.label }}</code>
  </p>
  <p>
    <label for="handle">Your name:</label>
    <input id="handle" type="text" placeholder="handle" required="true">
  </p>
  <div class="row">
    <form id="chatform">
      <table id="chat" class="table table-responsive">
        <tbody>
          {% for message in messages %}
          <tr>
            <td>{{ message.formatted_timestamp }}</td>
            <td>{{ message.handle }}</td>
            <td>{{ message.message }}</td>
          </tr>
          {% endfor %}
        </tbody>
        <tfoot>
          <tr>
            <td>Say something:</td>
            <td colspan=2>
              <input id="message" type="text" placeholder="message">
              <button type="submit" id="go">Say it</button>
            </td>
          </tfoot>
        </table>
      </form>
  </div>
  <script type="text/javascript">
//   $(function() {
//   // When we're using HTTPS, use WSS too.
//   var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
//   console.log(window.location.host);
//   console.log(window.location.pathname);
//   console.log(ws_scheme + '://' + window.location.host + window.location.pathname);
//   var chatsock = new ReconnectingWebSocket(ws_scheme + '://' + window.location.host + window.location.pathname);
//   console.log(chatsock);
//   chatsock.onopen = function open() {
//     console.log('WebSockets connection created.');
//   };
//
//   chatsock.onmessage = function(message) {
//       var data = JSON.parse(message.data);
//       var chat = $("#chat")
//       var ele = $('<tr></tr>')
//
//       ele.append(
//           $("<td></td>").text(data.timestamp)
//       )
//       ele.append(
//           $("<td></td>").text(data.handle)
//       )
//       ele.append(
//           $("<td></td>").text(data.message)
//       )
//
//       chat.append(ele)
//   };
//
//   $("#chatform").on("submit", function(event) {
//       var message = {
//           handle: $('#handle').val(),
//           message: $('#message').val(),
//       }
//       chatsock.send(JSON.stringify(message));
//       $("#message").val('').focus();
//       return false;
//   });
// });
$(function() {
    // When we're using HTTPS, use WSS too.
    var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
    // var chatsock = new ReconnectingWebSocket(ws_scheme + '://' + window.location.host + window.location.pathname);
    var chatsock = new ReconnectingWebSocket('ws://' + window.location.host + window.location.pathname);
    console.log(ws_scheme + '://' + window.location.host + window.location.pathname);
    chatsock.onmessage = function(message) {
      console.log(message);
        var data = JSON.parse(message.data);
        var chat = $("#chat")
        var ele = $('<tr></tr>')

        ele.append(
            $("<td></td>").text(data.timestamp)
        )
        ele.append(
            $("<td></td>").text(data.handle)
        )
        ele.append(
            $("<td></td>").text(data.message)
        )

        chat.append(ele)
    };
//     chatsock.onopen = function() {
//     chatsock.send("hello world");
// }
// // Call onopen directly if socket is already open
// if (chatsock.readyState == WebSocket.OPEN) chatsock.onopen();

    $("#chatform").on("submit", function(event) {
        var message = {
            handle: $('#handle').val(),
            message: $('#message').val(),
        }
        console.log(message);
        chatsock.send(JSON.stringify(message));
        $("#message").val('').focus();
        return false;
    });
});
</script>
{% endblock content %}